# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import kademlia_peer_pb2 as kademlia__peer__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in kademlia_peer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KademliaServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PING = channel.unary_unary(
                '/KademliaService/PING',
                request_serializer=kademlia__peer__pb2.PingCheck.SerializeToString,
                response_deserializer=kademlia__peer__pb2.NodeInfo.FromString,
                _registered_method=True)
        self.STORE = channel.unary_unary(
                '/KademliaService/STORE',
                request_serializer=kademlia__peer__pb2.StoreRequest.SerializeToString,
                response_deserializer=kademlia__peer__pb2.StoreResponse.FromString,
                _registered_method=True)
        self.FIND_NODE = channel.unary_unary(
                '/KademliaService/FIND_NODE',
                request_serializer=kademlia__peer__pb2.LookupRequest.SerializeToString,
                response_deserializer=kademlia__peer__pb2.LookupResponse.FromString,
                _registered_method=True)
        self.FIND_VALUE = channel.unary_unary(
                '/KademliaService/FIND_VALUE',
                request_serializer=kademlia__peer__pb2.LookupRequest.SerializeToString,
                response_deserializer=kademlia__peer__pb2.ValueResponse.FromString,
                _registered_method=True)
        self.ROUTING_TABLE_DUMP = channel.unary_unary(
                '/KademliaService/ROUTING_TABLE_DUMP',
                request_serializer=kademlia__peer__pb2.RoutingTableDumpRequest.SerializeToString,
                response_deserializer=kademlia__peer__pb2.RoutingTableDumpResponse.FromString,
                _registered_method=True)
        self.DATA_DUMP = channel.unary_unary(
                '/KademliaService/DATA_DUMP',
                request_serializer=kademlia__peer__pb2.DataDumpRequest.SerializeToString,
                response_deserializer=kademlia__peer__pb2.DataDumpResponse.FromString,
                _registered_method=True)
        self.HEAL_REPLICAS = channel.unary_unary(
                '/KademliaService/HEAL_REPLICAS',
                request_serializer=kademlia__peer__pb2.HealReplicasRequest.SerializeToString,
                response_deserializer=kademlia__peer__pb2.HealReplicasResponse.FromString,
                _registered_method=True)


class KademliaServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PING(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def STORE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FIND_NODE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FIND_VALUE(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ROUTING_TABLE_DUMP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DATA_DUMP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HEAL_REPLICAS(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KademliaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PING': grpc.unary_unary_rpc_method_handler(
                    servicer.PING,
                    request_deserializer=kademlia__peer__pb2.PingCheck.FromString,
                    response_serializer=kademlia__peer__pb2.NodeInfo.SerializeToString,
            ),
            'STORE': grpc.unary_unary_rpc_method_handler(
                    servicer.STORE,
                    request_deserializer=kademlia__peer__pb2.StoreRequest.FromString,
                    response_serializer=kademlia__peer__pb2.StoreResponse.SerializeToString,
            ),
            'FIND_NODE': grpc.unary_unary_rpc_method_handler(
                    servicer.FIND_NODE,
                    request_deserializer=kademlia__peer__pb2.LookupRequest.FromString,
                    response_serializer=kademlia__peer__pb2.LookupResponse.SerializeToString,
            ),
            'FIND_VALUE': grpc.unary_unary_rpc_method_handler(
                    servicer.FIND_VALUE,
                    request_deserializer=kademlia__peer__pb2.LookupRequest.FromString,
                    response_serializer=kademlia__peer__pb2.ValueResponse.SerializeToString,
            ),
            'ROUTING_TABLE_DUMP': grpc.unary_unary_rpc_method_handler(
                    servicer.ROUTING_TABLE_DUMP,
                    request_deserializer=kademlia__peer__pb2.RoutingTableDumpRequest.FromString,
                    response_serializer=kademlia__peer__pb2.RoutingTableDumpResponse.SerializeToString,
            ),
            'DATA_DUMP': grpc.unary_unary_rpc_method_handler(
                    servicer.DATA_DUMP,
                    request_deserializer=kademlia__peer__pb2.DataDumpRequest.FromString,
                    response_serializer=kademlia__peer__pb2.DataDumpResponse.SerializeToString,
            ),
            'HEAL_REPLICAS': grpc.unary_unary_rpc_method_handler(
                    servicer.HEAL_REPLICAS,
                    request_deserializer=kademlia__peer__pb2.HealReplicasRequest.FromString,
                    response_serializer=kademlia__peer__pb2.HealReplicasResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KademliaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('KademliaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KademliaService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PING(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KademliaService/PING',
            kademlia__peer__pb2.PingCheck.SerializeToString,
            kademlia__peer__pb2.NodeInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def STORE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KademliaService/STORE',
            kademlia__peer__pb2.StoreRequest.SerializeToString,
            kademlia__peer__pb2.StoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FIND_NODE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KademliaService/FIND_NODE',
            kademlia__peer__pb2.LookupRequest.SerializeToString,
            kademlia__peer__pb2.LookupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FIND_VALUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KademliaService/FIND_VALUE',
            kademlia__peer__pb2.LookupRequest.SerializeToString,
            kademlia__peer__pb2.ValueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ROUTING_TABLE_DUMP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KademliaService/ROUTING_TABLE_DUMP',
            kademlia__peer__pb2.RoutingTableDumpRequest.SerializeToString,
            kademlia__peer__pb2.RoutingTableDumpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DATA_DUMP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KademliaService/DATA_DUMP',
            kademlia__peer__pb2.DataDumpRequest.SerializeToString,
            kademlia__peer__pb2.DataDumpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HEAL_REPLICAS(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/KademliaService/HEAL_REPLICAS',
            kademlia__peer__pb2.HealReplicasRequest.SerializeToString,
            kademlia__peer__pb2.HealReplicasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
