// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.27.2
// source: kademlia_peer.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingCheck) Reset() {
	*x = PingCheck{}
	mi := &file_kademlia_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCheck) ProtoMessage() {}

func (x *PingCheck) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCheck.ProtoReflect.Descriptor instead.
func (*PingCheck) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{0}
}

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Id   string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_kademlia_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NodeID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NodeID) Reset() {
	*x = NodeID{}
	mi := &file_kademlia_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeID) ProtoMessage() {}

func (x *NodeID) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeID.ProtoReflect.Descriptor instead.
func (*NodeID) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{2}
}

func (x *NodeID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_kademlia_peer_proto protoreflect.FileDescriptor

var file_kademlia_peer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0b, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x22, 0x3e, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x18, 0x0a, 0x06, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0x57, 0x0a, 0x0f,
	0x4b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x1f, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x12, 0x0a, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x1a, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x00,
	0x12, 0x23, 0x0a, 0x09, 0x46, 0x49, 0x4e, 0x44, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x12, 0x07, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x44, 0x1a, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x00, 0x30, 0x01, 0x42, 0x12, 0x5a, 0x10, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69,
	0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_kademlia_peer_proto_rawDescOnce sync.Once
	file_kademlia_peer_proto_rawDescData = file_kademlia_peer_proto_rawDesc
)

func file_kademlia_peer_proto_rawDescGZIP() []byte {
	file_kademlia_peer_proto_rawDescOnce.Do(func() {
		file_kademlia_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_kademlia_peer_proto_rawDescData)
	})
	return file_kademlia_peer_proto_rawDescData
}

var file_kademlia_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_kademlia_peer_proto_goTypes = []any{
	(*PingCheck)(nil), // 0: PingCheck
	(*NodeInfo)(nil),  // 1: NodeInfo
	(*NodeID)(nil),    // 2: NodeID
}
var file_kademlia_peer_proto_depIdxs = []int32{
	0, // 0: KademliaService.PING:input_type -> PingCheck
	2, // 1: KademliaService.FIND_NODE:input_type -> NodeID
	1, // 2: KademliaService.PING:output_type -> NodeInfo
	1, // 3: KademliaService.FIND_NODE:output_type -> NodeInfo
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_kademlia_peer_proto_init() }
func file_kademlia_peer_proto_init() {
	if File_kademlia_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kademlia_peer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kademlia_peer_proto_goTypes,
		DependencyIndexes: file_kademlia_peer_proto_depIdxs,
		MessageInfos:      file_kademlia_peer_proto_msgTypes,
	}.Build()
	File_kademlia_peer_proto = out.File
	file_kademlia_peer_proto_rawDesc = nil
	file_kademlia_peer_proto_goTypes = nil
	file_kademlia_peer_proto_depIdxs = nil
}
