// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.27.2
// source: kademlia_peer.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip   string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Id   string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_kademlia_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NodeInfoLookup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeDetails      *NodeInfo `protobuf:"bytes,1,opt,name=nodeDetails,proto3" json:"nodeDetails,omitempty"`
	DistanceToTarget uint32    `protobuf:"varint,2,opt,name=distanceToTarget,proto3" json:"distanceToTarget,omitempty"`
}

func (x *NodeInfoLookup) Reset() {
	*x = NodeInfoLookup{}
	mi := &file_kademlia_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoLookup) ProtoMessage() {}

func (x *NodeInfoLookup) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoLookup.ProtoReflect.Descriptor instead.
func (*NodeInfoLookup) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfoLookup) GetNodeDetails() *NodeInfo {
	if x != nil {
		return x.NodeDetails
	}
	return nil
}

func (x *NodeInfoLookup) GetDistanceToTarget() uint32 {
	if x != nil {
		return x.DistanceToTarget
	}
	return 0
}

type PingCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingCheck) Reset() {
	*x = PingCheck{}
	mi := &file_kademlia_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCheck) ProtoMessage() {}

func (x *PingCheck) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCheck.ProtoReflect.Descriptor instead.
func (*PingCheck) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{2}
}

type StoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value       int32     `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Requester   *NodeInfo `protobuf:"bytes,3,opt,name=requester,proto3,oneof" json:"requester,omitempty"`
	MagicCookie *uint64   `protobuf:"varint,4,opt,name=magicCookie,proto3,oneof" json:"magicCookie,omitempty"`
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_kademlia_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{3}
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StoreRequest) GetRequester() *NodeInfo {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *StoreRequest) GetMagicCookie() uint64 {
	if x != nil && x.MagicCookie != nil {
		return *x.MagicCookie
	}
	return 0
}

type StoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataNodes []*NodeInfoLookup `protobuf:"bytes,2,rep,name=dataNodes,proto3" json:"dataNodes,omitempty"`
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{4}
}

func (x *StoreResponse) GetDataNodes() []*NodeInfoLookup {
	if x != nil {
		return x.DataNodes
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Requester   *NodeInfo `protobuf:"bytes,1,opt,name=requester,proto3,oneof" json:"requester,omitempty"`
	Target      string    `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	MagicCookie *uint64   `protobuf:"varint,3,opt,name=magicCookie,proto3,oneof" json:"magicCookie,omitempty"`
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_kademlia_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{5}
}

func (x *LookupRequest) GetRequester() *NodeInfo {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *LookupRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LookupRequest) GetMagicCookie() uint64 {
	if x != nil && x.MagicCookie != nil {
		return *x.MagicCookie
	}
	return 0
}

type LookupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nodes []*NodeInfoLookup `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{6}
}

func (x *LookupResponse) GetNodes() []*NodeInfoLookup {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type ValueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value *int32            `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Nodes []*NodeInfoLookup `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
}

func (x *ValueResponse) Reset() {
	*x = ValueResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueResponse) ProtoMessage() {}

func (x *ValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueResponse.ProtoReflect.Descriptor instead.
func (*ValueResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{7}
}

func (x *ValueResponse) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ValueResponse) GetNodes() []*NodeInfoLookup {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_kademlia_peer_proto protoreflect.FileDescriptor

var file_kademlia_peer_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a, 0x0e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66,
	0x6f, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x12, 0x2b, 0x0a, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e,
	0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x6e, 0x6f, 0x64, 0x65, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x54, 0x6f, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x10,
	0x64, 0x69, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x54, 0x6f, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x22, 0x0b, 0x0a, 0x09, 0x50, 0x69, 0x6e, 0x67, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x22, 0xa9, 0x01,
	0x0a, 0x0c, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65,
	0x72, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x0b, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x43, 0x6f, 0x6f,
	0x6b, 0x69, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x67,
	0x69, 0x63, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6d, 0x61,
	0x67, 0x69, 0x63, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x22, 0x3e, 0x0a, 0x0d, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x61,
	0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x09,
	0x64, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x64, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x0d, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x09, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x12, 0x25, 0x0a, 0x0b, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x48, 0x01, 0x52, 0x0b, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x43,
	0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x65, 0x72, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x6d, 0x61, 0x67, 0x69, 0x63,
	0x43, 0x6f, 0x6f, 0x6b, 0x69, 0x65, 0x22, 0x37, 0x0a, 0x0e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x6e, 0x6f, 0x64, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x05, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x22,
	0x5b, 0x0a, 0x0d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48,
	0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x25, 0x0a, 0x05, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x52, 0x05, 0x6e, 0x6f, 0x64,
	0x65, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xbc, 0x01, 0x0a,
	0x0f, 0x4b, 0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x50, 0x49, 0x4e, 0x47, 0x12, 0x0a, 0x2e, 0x50, 0x69, 0x6e, 0x67, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x1a, 0x09, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x00, 0x12, 0x28, 0x0a, 0x05, 0x53, 0x54, 0x4f, 0x52, 0x45, 0x12, 0x0d, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x09, 0x46,
	0x49, 0x4e, 0x44, 0x5f, 0x4e, 0x4f, 0x44, 0x45, 0x12, 0x0e, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x0a, 0x46,
	0x49, 0x4e, 0x44, 0x5f, 0x56, 0x41, 0x4c, 0x55, 0x45, 0x12, 0x0e, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x6b,
	0x61, 0x64, 0x65, 0x6d, 0x6c, 0x69, 0x61, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kademlia_peer_proto_rawDescOnce sync.Once
	file_kademlia_peer_proto_rawDescData = file_kademlia_peer_proto_rawDesc
)

func file_kademlia_peer_proto_rawDescGZIP() []byte {
	file_kademlia_peer_proto_rawDescOnce.Do(func() {
		file_kademlia_peer_proto_rawDescData = protoimpl.X.CompressGZIP(file_kademlia_peer_proto_rawDescData)
	})
	return file_kademlia_peer_proto_rawDescData
}

var file_kademlia_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_kademlia_peer_proto_goTypes = []any{
	(*NodeInfo)(nil),       // 0: NodeInfo
	(*NodeInfoLookup)(nil), // 1: NodeInfoLookup
	(*PingCheck)(nil),      // 2: PingCheck
	(*StoreRequest)(nil),   // 3: StoreRequest
	(*StoreResponse)(nil),  // 4: StoreResponse
	(*LookupRequest)(nil),  // 5: LookupRequest
	(*LookupResponse)(nil), // 6: LookupResponse
	(*ValueResponse)(nil),  // 7: ValueResponse
}
var file_kademlia_peer_proto_depIdxs = []int32{
	0,  // 0: NodeInfoLookup.nodeDetails:type_name -> NodeInfo
	0,  // 1: StoreRequest.requester:type_name -> NodeInfo
	1,  // 2: StoreResponse.dataNodes:type_name -> NodeInfoLookup
	0,  // 3: LookupRequest.requester:type_name -> NodeInfo
	1,  // 4: LookupResponse.nodes:type_name -> NodeInfoLookup
	1,  // 5: ValueResponse.nodes:type_name -> NodeInfoLookup
	2,  // 6: KademliaService.PING:input_type -> PingCheck
	3,  // 7: KademliaService.STORE:input_type -> StoreRequest
	5,  // 8: KademliaService.FIND_NODE:input_type -> LookupRequest
	5,  // 9: KademliaService.FIND_VALUE:input_type -> LookupRequest
	0,  // 10: KademliaService.PING:output_type -> NodeInfo
	4,  // 11: KademliaService.STORE:output_type -> StoreResponse
	6,  // 12: KademliaService.FIND_NODE:output_type -> LookupResponse
	7,  // 13: KademliaService.FIND_VALUE:output_type -> ValueResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_kademlia_peer_proto_init() }
func file_kademlia_peer_proto_init() {
	if File_kademlia_peer_proto != nil {
		return
	}
	file_kademlia_peer_proto_msgTypes[3].OneofWrappers = []any{}
	file_kademlia_peer_proto_msgTypes[5].OneofWrappers = []any{}
	file_kademlia_peer_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kademlia_peer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kademlia_peer_proto_goTypes,
		DependencyIndexes: file_kademlia_peer_proto_depIdxs,
		MessageInfos:      file_kademlia_peer_proto_msgTypes,
	}.Build()
	File_kademlia_peer_proto = out.File
	file_kademlia_peer_proto_rawDesc = nil
	file_kademlia_peer_proto_goTypes = nil
	file_kademlia_peer_proto_depIdxs = nil
}
