// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.2
// source: kademlia_peer.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_kademlia_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NodeInfoLookup struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeDetails      *NodeInfo              `protobuf:"bytes,1,opt,name=nodeDetails,proto3" json:"nodeDetails,omitempty"`
	DistanceToTarget uint32                 `protobuf:"varint,2,opt,name=distanceToTarget,proto3" json:"distanceToTarget,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeInfoLookup) Reset() {
	*x = NodeInfoLookup{}
	mi := &file_kademlia_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoLookup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoLookup) ProtoMessage() {}

func (x *NodeInfoLookup) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoLookup.ProtoReflect.Descriptor instead.
func (*NodeInfoLookup) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfoLookup) GetNodeDetails() *NodeInfo {
	if x != nil {
		return x.NodeDetails
	}
	return nil
}

func (x *NodeInfoLookup) GetDistanceToTarget() uint32 {
	if x != nil {
		return x.DistanceToTarget
	}
	return 0
}

type PingCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingCheck) Reset() {
	*x = PingCheck{}
	mi := &file_kademlia_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingCheck) ProtoMessage() {}

func (x *PingCheck) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingCheck.ProtoReflect.Descriptor instead.
func (*PingCheck) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{2}
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Requester     *NodeInfo              `protobuf:"bytes,3,opt,name=requester,proto3,oneof" json:"requester,omitempty"`
	MagicCookie   *uint64                `protobuf:"varint,4,opt,name=magicCookie,proto3,oneof" json:"magicCookie,omitempty"`
	Version       *int32                 `protobuf:"varint,5,opt,name=version,proto3,oneof" json:"version,omitempty"`
	Leaser        *string                `protobuf:"bytes,6,opt,name=leaser,proto3,oneof" json:"leaser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_kademlia_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{3}
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *StoreRequest) GetRequester() *NodeInfo {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *StoreRequest) GetMagicCookie() uint64 {
	if x != nil && x.MagicCookie != nil {
		return *x.MagicCookie
	}
	return 0
}

func (x *StoreRequest) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *StoreRequest) GetLeaser() string {
	if x != nil && x.Leaser != nil {
		return *x.Leaser
	}
	return ""
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataNodes     []*NodeInfoLookup      `protobuf:"bytes,2,rep,name=dataNodes,proto3" json:"dataNodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{4}
}

func (x *StoreResponse) GetDataNodes() []*NodeInfoLookup {
	if x != nil {
		return x.DataNodes
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requester     *NodeInfo              `protobuf:"bytes,1,opt,name=requester,proto3,oneof" json:"requester,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	MagicCookie   *uint64                `protobuf:"varint,3,opt,name=magicCookie,proto3,oneof" json:"magicCookie,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_kademlia_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{5}
}

func (x *LookupRequest) GetRequester() *NodeInfo {
	if x != nil {
		return x.Requester
	}
	return nil
}

func (x *LookupRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *LookupRequest) GetMagicCookie() uint64 {
	if x != nil && x.MagicCookie != nil {
		return *x.MagicCookie
	}
	return 0
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfoLookup      `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{6}
}

func (x *LookupResponse) GetNodes() []*NodeInfoLookup {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type FoundData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[int32]int32        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FoundData) Reset() {
	*x = FoundData{}
	mi := &file_kademlia_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FoundData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoundData) ProtoMessage() {}

func (x *FoundData) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoundData.ProtoReflect.Descriptor instead.
func (*FoundData) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{7}
}

func (x *FoundData) GetData() map[int32]int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type ValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int32                 `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Nodes         []*NodeInfoLookup      `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Version       *int32                 `protobuf:"varint,3,opt,name=version,proto3,oneof" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueResponse) Reset() {
	*x = ValueResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueResponse) ProtoMessage() {}

func (x *ValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueResponse.ProtoReflect.Descriptor instead.
func (*ValueResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{8}
}

func (x *ValueResponse) GetValue() int32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ValueResponse) GetNodes() []*NodeInfoLookup {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ValueResponse) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

type RoutingTableDumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTableDumpRequest) Reset() {
	*x = RoutingTableDumpRequest{}
	mi := &file_kademlia_peer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTableDumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTableDumpRequest) ProtoMessage() {}

func (x *RoutingTableDumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTableDumpRequest.ProtoReflect.Descriptor instead.
func (*RoutingTableDumpRequest) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{9}
}

type NodeInfoList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfoList) Reset() {
	*x = NodeInfoList{}
	mi := &file_kademlia_peer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfoList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfoList) ProtoMessage() {}

func (x *NodeInfoList) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfoList.ProtoReflect.Descriptor instead.
func (*NodeInfoList) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{10}
}

func (x *NodeInfoList) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type RoutingTableDumpResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Pairs         map[uint32]*NodeInfoList `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutingTableDumpResponse) Reset() {
	*x = RoutingTableDumpResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutingTableDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingTableDumpResponse) ProtoMessage() {}

func (x *RoutingTableDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingTableDumpResponse.ProtoReflect.Descriptor instead.
func (*RoutingTableDumpResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{11}
}

func (x *RoutingTableDumpResponse) GetPairs() map[uint32]*NodeInfoList {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type DataDumpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDumpRequest) Reset() {
	*x = DataDumpRequest{}
	mi := &file_kademlia_peer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDumpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDumpRequest) ProtoMessage() {}

func (x *DataDumpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDumpRequest.ProtoReflect.Descriptor instead.
func (*DataDumpRequest) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{12}
}

type DataDumpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         map[string]int32       `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Versions      map[string]int32       `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Leasers       map[string]string      `protobuf:"bytes,3,rep,name=leasers,proto3" json:"leasers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataDumpResponse) Reset() {
	*x = DataDumpResponse{}
	mi := &file_kademlia_peer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataDumpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDumpResponse) ProtoMessage() {}

func (x *DataDumpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kademlia_peer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDumpResponse.ProtoReflect.Descriptor instead.
func (*DataDumpResponse) Descriptor() ([]byte, []int) {
	return file_kademlia_peer_proto_rawDescGZIP(), []int{13}
}

func (x *DataDumpResponse) GetPairs() map[string]int32 {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *DataDumpResponse) GetVersions() map[string]int32 {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *DataDumpResponse) GetLeasers() map[string]string {
	if x != nil {
		return x.Leasers
	}
	return nil
}

var File_kademlia_peer_proto protoreflect.FileDescriptor

const file_kademlia_peer_proto_rawDesc = "" +
	"\n" +
	"\x13kademlia_peer.proto\">\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\"i\n" +
	"\x0eNodeInfoLookup\x12+\n" +
	"\vnodeDetails\x18\x01 \x01(\v2\t.NodeInfoR\vnodeDetails\x12*\n" +
	"\x10distanceToTarget\x18\x02 \x01(\rR\x10distanceToTarget\"\v\n" +
	"\tPingCheck\"\xfc\x01\n" +
	"\fStoreRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12,\n" +
	"\trequester\x18\x03 \x01(\v2\t.NodeInfoH\x00R\trequester\x88\x01\x01\x12%\n" +
	"\vmagicCookie\x18\x04 \x01(\x04H\x01R\vmagicCookie\x88\x01\x01\x12\x1d\n" +
	"\aversion\x18\x05 \x01(\x05H\x02R\aversion\x88\x01\x01\x12\x1b\n" +
	"\x06leaser\x18\x06 \x01(\tH\x03R\x06leaser\x88\x01\x01B\f\n" +
	"\n" +
	"_requesterB\x0e\n" +
	"\f_magicCookieB\n" +
	"\n" +
	"\b_versionB\t\n" +
	"\a_leaser\">\n" +
	"\rStoreResponse\x12-\n" +
	"\tdataNodes\x18\x02 \x03(\v2\x0f.NodeInfoLookupR\tdataNodes\"\x9a\x01\n" +
	"\rLookupRequest\x12,\n" +
	"\trequester\x18\x01 \x01(\v2\t.NodeInfoH\x00R\trequester\x88\x01\x01\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12%\n" +
	"\vmagicCookie\x18\x03 \x01(\x04H\x01R\vmagicCookie\x88\x01\x01B\f\n" +
	"\n" +
	"_requesterB\x0e\n" +
	"\f_magicCookie\"7\n" +
	"\x0eLookupResponse\x12%\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0f.NodeInfoLookupR\x05nodes\"n\n" +
	"\tFoundData\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.FoundData.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x86\x01\n" +
	"\rValueResponse\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x05H\x00R\x05value\x88\x01\x01\x12%\n" +
	"\x05nodes\x18\x02 \x03(\v2\x0f.NodeInfoLookupR\x05nodes\x12\x1d\n" +
	"\aversion\x18\x03 \x01(\x05H\x01R\aversion\x88\x01\x01B\b\n" +
	"\x06_valueB\n" +
	"\n" +
	"\b_version\"\x19\n" +
	"\x17RoutingTableDumpRequest\"/\n" +
	"\fNodeInfoList\x12\x1f\n" +
	"\x05nodes\x18\x01 \x03(\v2\t.NodeInfoR\x05nodes\"\x9f\x01\n" +
	"\x18RoutingTableDumpResponse\x12:\n" +
	"\x05pairs\x18\x01 \x03(\v2$.RoutingTableDumpResponse.PairsEntryR\x05pairs\x1aG\n" +
	"\n" +
	"PairsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12#\n" +
	"\x05value\x18\x02 \x01(\v2\r.NodeInfoListR\x05value:\x028\x01\"\x11\n" +
	"\x0fDataDumpRequest\"\xf0\x02\n" +
	"\x10DataDumpResponse\x122\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1c.DataDumpResponse.PairsEntryR\x05pairs\x12;\n" +
	"\bversions\x18\x02 \x03(\v2\x1f.DataDumpResponse.VersionsEntryR\bversions\x128\n" +
	"\aleasers\x18\x03 \x03(\v2\x1e.DataDumpResponse.LeasersEntryR\aleasers\x1a8\n" +
	"\n" +
	"PairsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a;\n" +
	"\rVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1a:\n" +
	"\fLeasersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xbd\x02\n" +
	"\x0fKademliaService\x12\x1f\n" +
	"\x04PING\x12\n" +
	".PingCheck\x1a\t.NodeInfo\"\x00\x12(\n" +
	"\x05STORE\x12\r.StoreRequest\x1a\x0e.StoreResponse\"\x00\x12.\n" +
	"\tFIND_NODE\x12\x0e.LookupRequest\x1a\x0f.LookupResponse\"\x00\x12.\n" +
	"\n" +
	"FIND_VALUE\x12\x0e.LookupRequest\x1a\x0e.ValueResponse\"\x00\x12K\n" +
	"\x12ROUTING_TABLE_DUMP\x12\x18.RoutingTableDumpRequest\x1a\x19.RoutingTableDumpResponse\"\x00\x122\n" +
	"\tDATA_DUMP\x12\x10.DataDumpRequest\x1a\x11.DataDumpResponse\"\x00B\x12Z\x10kademlia/serviceb\x06proto3"

var (
	file_kademlia_peer_proto_rawDescOnce sync.Once
	file_kademlia_peer_proto_rawDescData []byte
)

func file_kademlia_peer_proto_rawDescGZIP() []byte {
	file_kademlia_peer_proto_rawDescOnce.Do(func() {
		file_kademlia_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kademlia_peer_proto_rawDesc), len(file_kademlia_peer_proto_rawDesc)))
	})
	return file_kademlia_peer_proto_rawDescData
}

var file_kademlia_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_kademlia_peer_proto_goTypes = []any{
	(*NodeInfo)(nil),                 // 0: NodeInfo
	(*NodeInfoLookup)(nil),           // 1: NodeInfoLookup
	(*PingCheck)(nil),                // 2: PingCheck
	(*StoreRequest)(nil),             // 3: StoreRequest
	(*StoreResponse)(nil),            // 4: StoreResponse
	(*LookupRequest)(nil),            // 5: LookupRequest
	(*LookupResponse)(nil),           // 6: LookupResponse
	(*FoundData)(nil),                // 7: FoundData
	(*ValueResponse)(nil),            // 8: ValueResponse
	(*RoutingTableDumpRequest)(nil),  // 9: RoutingTableDumpRequest
	(*NodeInfoList)(nil),             // 10: NodeInfoList
	(*RoutingTableDumpResponse)(nil), // 11: RoutingTableDumpResponse
	(*DataDumpRequest)(nil),          // 12: DataDumpRequest
	(*DataDumpResponse)(nil),         // 13: DataDumpResponse
	nil,                              // 14: FoundData.DataEntry
	nil,                              // 15: RoutingTableDumpResponse.PairsEntry
	nil,                              // 16: DataDumpResponse.PairsEntry
	nil,                              // 17: DataDumpResponse.VersionsEntry
	nil,                              // 18: DataDumpResponse.LeasersEntry
}
var file_kademlia_peer_proto_depIdxs = []int32{
	0,  // 0: NodeInfoLookup.nodeDetails:type_name -> NodeInfo
	0,  // 1: StoreRequest.requester:type_name -> NodeInfo
	1,  // 2: StoreResponse.dataNodes:type_name -> NodeInfoLookup
	0,  // 3: LookupRequest.requester:type_name -> NodeInfo
	1,  // 4: LookupResponse.nodes:type_name -> NodeInfoLookup
	14, // 5: FoundData.data:type_name -> FoundData.DataEntry
	1,  // 6: ValueResponse.nodes:type_name -> NodeInfoLookup
	0,  // 7: NodeInfoList.nodes:type_name -> NodeInfo
	15, // 8: RoutingTableDumpResponse.pairs:type_name -> RoutingTableDumpResponse.PairsEntry
	16, // 9: DataDumpResponse.pairs:type_name -> DataDumpResponse.PairsEntry
	17, // 10: DataDumpResponse.versions:type_name -> DataDumpResponse.VersionsEntry
	18, // 11: DataDumpResponse.leasers:type_name -> DataDumpResponse.LeasersEntry
	10, // 12: RoutingTableDumpResponse.PairsEntry.value:type_name -> NodeInfoList
	2,  // 13: KademliaService.PING:input_type -> PingCheck
	3,  // 14: KademliaService.STORE:input_type -> StoreRequest
	5,  // 15: KademliaService.FIND_NODE:input_type -> LookupRequest
	5,  // 16: KademliaService.FIND_VALUE:input_type -> LookupRequest
	9,  // 17: KademliaService.ROUTING_TABLE_DUMP:input_type -> RoutingTableDumpRequest
	12, // 18: KademliaService.DATA_DUMP:input_type -> DataDumpRequest
	0,  // 19: KademliaService.PING:output_type -> NodeInfo
	4,  // 20: KademliaService.STORE:output_type -> StoreResponse
	6,  // 21: KademliaService.FIND_NODE:output_type -> LookupResponse
	8,  // 22: KademliaService.FIND_VALUE:output_type -> ValueResponse
	11, // 23: KademliaService.ROUTING_TABLE_DUMP:output_type -> RoutingTableDumpResponse
	13, // 24: KademliaService.DATA_DUMP:output_type -> DataDumpResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_kademlia_peer_proto_init() }
func file_kademlia_peer_proto_init() {
	if File_kademlia_peer_proto != nil {
		return
	}
	file_kademlia_peer_proto_msgTypes[3].OneofWrappers = []any{}
	file_kademlia_peer_proto_msgTypes[5].OneofWrappers = []any{}
	file_kademlia_peer_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kademlia_peer_proto_rawDesc), len(file_kademlia_peer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kademlia_peer_proto_goTypes,
		DependencyIndexes: file_kademlia_peer_proto_depIdxs,
		MessageInfos:      file_kademlia_peer_proto_msgTypes,
	}.Build()
	File_kademlia_peer_proto = out.File
	file_kademlia_peer_proto_goTypes = nil
	file_kademlia_peer_proto_depIdxs = nil
}
